### ISSUE TITLE
German and Chinese localisations

### ISSUE THREAD

**Issue by yue-dongchen** [dmitriy-ilchenko/QrAndBarcodeScanner#13]
I've been really impressed by the UI of this app. I'd now like to work on adding values for German and Chinese (my languages). I'll try to work on them in my spare time.

Regards,
Dongchen

**Comment by dmitriy-ilchenko** [comment]
Thank you, it would be really helpful.

**Comment by dyue05** [comment]
Regarding the name of this app, it's not really easy to be uniformly applied across all languages. Perhaps the displayed name could be shortened to "QBScan" or similar for a mulilingual (untranslatable) name. Your thoughts?

**Comment by dmitriy-ilchenko** [comment]
The name of the app can be translated, no? For example, in English it is "QR & Barcode Scanner", in Russian it is "Сканер QR и штрихкодов". I can't come up with any untranslatable name right now. If you have any ideas, feel free to share.

**Comment by dyue05** [comment]
I personally think "QBScan" is quite good. If you think that's not suitable, I'll just translate it literally.

**Comment by dmitriy-ilchenko** [comment]
Yes, I think literal translation will be fine for now.

**Comment by dmitriy-ilchenko** [comment]
Hello. If you are still interested in this issue, I created a project on [Transifex](https://www.transifex.com/a-302/qr-barcode-scanner/dashboard/). You can add the Chinese translation there or create a PR. Thanks again for your help.

**Comment by tifriis208** [comment]
Thanks, I propose to deal with the french translation. Love your app :+1:

**Comment by dyue05** [comment]
Sorry for the delay. I plan to finish the Chinese ones this weekend.

**Comment by tifriis208** [comment]
> Thanks, I propose to deal with the french translation. Love your app

When I try to join the team in transiflex, French isn't an available language :C
Could you add it ? Thanks !

**Comment by dmitriy-ilchenko** [comment]
> > Thanks, I propose to deal with the french translation. Love your app
> 
> When I try to join the team in transiflex, French isn't an available language :C
> Could you add it ? Thanks !

That's weird. https://www.transifex.com/a-302/qr-barcode-scanner/language/fr_FR/

**Comment by tifriis208** [comment]
> > > Thanks, I propose to deal with the french translation. Love your app
> > 
> > 
> > When I try to join the team in transiflex, French isn't an available language :C
> > Could you add it ? Thanks !
> 
> That's weird. https://www.transifex.com/a-302/qr-barcode-scanner/language/fr_FR/

Yes, really weird. I got a 404 error with your link. A sent a message to transiflex to inform them of this issue.

**Comment by yue-dongchen** [comment]
@dmitriy-ilchenko ,
I don't seem to have been approved on Transifex one week after sending a request. Could you please check?

Thanks.

**Comment by tifriis208** [comment]
Same for me, and I think there is a bug with French langage. Could you delete it (like this, I would be able to "ask a langage"). thanks

**Comment by dmitriy-ilchenko** [comment]
@yue-dongchen Sorry for the delay, I guess I approved you.
@tifriis208 I guess that the problem was that I didn't approved you to join the team. Sorry for the inconvenience, I am not very familiar with Transifex. Could you please try now?

**Comment by tifriis208** [comment]
@dmitriy-ilchenko yes it worked.  Scrat15 made an huge and fast work. I finished the french translation and corrected some mistakes. It's all goof for french langage :)

**Comment by yue-dongchen** [comment]
I had a look at the simplified Chinese (zh_CN) translations and they seem fine. I'll close this for now.
