### ISSUE TITLE
Please add the option for Custom Search Engines

### ISSUE THREAD

**Issue by derei** [dmitriy-ilchenko/QrAndBarcodeScanner#19]
I noticed that your app is using Google for web search and there doesn't seem to be any way to change that.
Coul you please add an option for other search engines? I personally use Duckduckgo and I'm sure many other users think the same.

Best wishes!

**Comment by dmitriy-ilchenko** [comment]
Hello. When you click "Search on the web" the app should show you a dialog in which you can choose any app that can handle web search, including DuckDuckGo. Or you mean something else?

![photo_2020-09-17_13-44-48](https://user-images.githubusercontent.com/59684939/93460518-fe8edd00-f8eb-11ea-8411-95d733122dde.jpg)

**Comment by derei** [comment]
Yes, this is what I mean, except that it never happened for me. It went directly to Google. I have Kiwi Browser installed, with DDG as default engine.
If you can provide me with an email address, I could send you a screen recording.

**Comment by dmitriy-ilchenko** [comment]
I've managed to identify the problem. For some reasons, Kiwi Browser does not support handling intents for web search (with action = Intent.ACTION_WEB_SEARCH). In your case, it seems that Google is the only app on your device which can handle this intent, thats why it went directly there. In my case, there are several apps which can handle this intent, thats why OS showed me a dialog to choose an app. 
Kiwi Browser may be openable from other apps which send intents containing destination URLs. I can add an option to select a search engine. In that case I would have to construct a search URL depending on selected search engine. But it doesn't seem to me as the right way to implement web search.
Maybe I can open an issue in Kiwi Browser's repository and ask them to support Intent.ACTION_WEB_SEARCH.
What do you think?

**Comment by dmitriy-ilchenko** [comment]
If you are still interested, I opened the [issue](https://github.com/kiwibrowser/src/issues/174) in Kiwi Browser's repository to support Intent.ACTION_WEB_SEARCH. Also I decided to implement choosing search engine in my app. Hopefully this feature will be implemented in the next release. It can take several days or so.

**Comment by derei** [comment]
great one, thanks! I could see the devs behind kiwi browser take the feedback rather serious, so it may actually happen :D
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Sep 18, 2020, 14:36 by notifications@github.com:

**Comment by dmitriy-ilchenko** [comment]
This feature was implemented in v1.4. Soon it will be available in app stores. I will leave this issue open for some time so if you are interested you can leave a feedback or report a bug.
