### ISSUE TITLE
add pt_BR strings

### ISSUE THREAD

**Issue by aevw** [dmitriy-ilchenko/QrAndBarcodeScanner#20]
Hello devs,

Here are translated strings for [pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/rq-c.xml),

btw the app is very good!

Thanks

**Comment by dmitriy-ilchenko** [comment]
Thanks a lot! Added this translation in [this commit](https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner/commit/6a24ef6c15fd8eb106ee439c3bf24899784d32e4). It will appear in the next release.

**Comment by aevw** [comment]
I found some small typos and errors, please copy once again that same file, now it's much better. You can see changes there. Thanks.

**Comment by dmitriy-ilchenko** [comment]
Done. Thanks again!
