### ISSUE TITLE
Add share button

### ISSUE THREAD

**Issue by MarkSmz** [dmitriy-ilchenko/QrAndBarcodeScanner#22]
Hello,

I found the app yesterday via F-Droid and am positively surprised that it already supports so many functions. Thanks a lot for that. Also the handling is much easier and better than with the QR-scanners I have used so far.
The only feature I am missing is the classic sharing, so I can send the scanned QR code with/in other apps or transfer it to the PC.
So is it possible to add this?

**Comment by dmitriy-ilchenko** [comment]
Hello. Thank you for your feedback. Share buttons are already present. You can share as text or as image. Or you mean something else?
![Screenshot_20200919_200821_org barcodescanner](https://user-images.githubusercontent.com/59684939/93674907-70198780-fab4-11ea-91cf-50255aa7f16f.jpg)

**Comment by MarkSmz** [comment]
Ahh, okay.
I had overlooked that because the menu looks like an app selection at first.
In other apps the menu just looks different, because you can directly select a contact or a device to send it to.
Thanks for the quick answer.

This is a different subject, but will it be possible to add barcode search engines, such as Codecheck, or Open Food Facts?

**Comment by dmitriy-ilchenko** [comment]
Yes, it is possible. I guess I will implement it soon.

**Comment by MarkSmz** [comment]
Thanks for the effort
