### ISSUE TITLE
Doubling of slash

### ISSUE THREAD

**Issue by tjeulink** [dmitriy-ilchenko/QrAndBarcodeScanner#24]
Hi there, there seems to be a bug where / gets doubled when scanning a QR code for a wifi network. i've made some screenshots to show how to reproduce: https://imgur.com/a/iqzbGNo

As you can see, via android settings sharing a wifi network via QR code, then i screenshotted that and opened it as a picture in the QR and Barcode Scanner app, which resulted in the / being changed into //.

**Comment by dmitriy-ilchenko** [comment]
Hello. Thank you for reporting a bug. But I didn't manage to reproduce it. Are you using the latest version? (1.3) Could you please provide the whole password that causes the bug?

**Comment by tjeulink** [comment]
Yes, here's the password that caused it. Maybe android itself generated the QR code wrong? i have no idea tbh. just tried it again and i still have the same problem somehow. here's a picture of the QR code android generates unblurred. i can change my wifi passwords, i didn't want to share them first. [Here's an screenshot from the android10 settings QR code too](https://imgur.com/a/mIV7KGJ).
`D6ltubarawvo2q\O`

**Comment by dmitriy-ilchenko** [comment]
The slash was escaped by another slash, so the QR code actually contains two slashes. My app shows a password as it presented in a QR code, some other apps might unescape it first before showing it. I can implement the same behaviour in my app. What do you think?
