### ISSUE TITLE
[Feature Request] Add Quick Settings tile 

### ISSUE THREAD

**Issue by x2k13** [dmitriy-ilchenko/QrAndBarcodeScanner#33]
Thank you for this nice and clean app. It just does what I need.
Just one thing is missing IMHO, a tile for the Quick Settings. 
This would come in handy because the scanner could be launched even from the lock screen.
It would be great if you could implement this.

**Comment by dmitriy-ilchenko** [comment]
Hello. Thank you for your feedback. It is actually a great idea, I think I will implement this feature in the near future.

**Comment by x2k13** [comment]
> Hello. Thank you for your feedback. It is actually a great idea, I think I will implement this feature in the near future.

Thank you! Looking forward to it. 😀

**Comment by dmitriy-ilchenko** [comment]
Implemented in v1.5
