### ISSUE TITLE
Feature request: When reading a QR code with an app link, have an option to start the app without a store

### ISSUE THREAD

**Issue by MPeti1** [dmitriy-ilchenko/QrAndBarcodeScanner#36]
Currently if I scan a QR code that contains an app link, I'll be presented with the common options, plus "open in market" and "search on the web"

But there could be cases when the app is not in a store, or just not yet (because it's in development), or when I just don't want to open it through google play for privacy reasons. For these, there could be an option to open the app.

**Comment by dmitriy-ilchenko** [comment]
Yes, this makes sense, and it won't be hard to implement.

**Comment by dmitriy-ilchenko** [comment]
Resolved in v1.5
