### ISSUE TITLE
DataMatrix output image gets 2x horizontally

### ISSUE THREAD

**Issue by ins2d** [dmitriy-ilchenko/QrAndBarcodeScanner#43]
Sometimes get this wiered output for DataMatrix generation :)

![photo_2020-10-12_21-09-48](https://user-images.githubusercontent.com/20364046/95778801-8ab8d800-0cd1-11eb-9bfb-f2f42eeb7f22.jpg)

Text to reproduce/debug: LQqwkXiTF5FZwBN12MRdPfZHu9bpMwBXJW

**Comment by dmitriy-ilchenko** [comment]
It is a valid DataMatrix. Check [this](https://stackoverflow.com/questions/43476750/datamatrix-16x48-with-tcpdf-library-for-php) for example.
