### ISSUE TITLE
Wi-Fi Connection Setup Becomes Permanent 

### ISSUE THREAD

**Issue by Still34** [dmitriy-ilchenko/QrAndBarcodeScanner#45]
If a Wi-Fi network is registered using the app, the network cannot be edited or removed. Networks added by the app will have a "Available via <app name>" watermark next to the AP. Tested on Pixel 3 XL/latest R build.

Attempting to edit the network will result in the following dialog:

![image](https://user-images.githubusercontent.com/5843208/97103458-951e9d00-16e7-11eb-8777-6ab0bebca940.png)

**Comment by dmitriy-ilchenko** [comment]
It seems that the "Action is not allowed" errors are caused by device administrator apps. Please try to follow the [instruction](https://www.htcexodus.com/mea-en/support/exodus-one/category_howto/how-do-i-enable-or-disable-device-administrators-app.html) and see if there are any apps with admin privileges.

**Comment by Still34** [comment]
See, that's what I thought as well - but no, there are no device admins registered.

**Comment by Still34** [comment]
Closing as I'm guessing this is an Android-specific bug.

**Comment by jmichael2497** [comment]
found workaround to 3rd party app added wifi like with this qr and barcode scanner app, that only shows in active list with "Available via (app)", that cannot be edited in any way, and does not show in saved networks.

temporarily disable the app, the entry disappears. enable app again, the entry stays gone.

**Comment by fungs** [comment]
Same issue on Android 13 (e/OS). No way to temporary disable the QR code scanner app. I suppose the only way to make the entries go away, is to uninstall and reinstall the scanner app.

**Comment by fungs** [comment]
Ok, I found a way described here: https://support.qrqrq.com/hc/en-us/articles/11480787822233-Unable-to-delete-Wi-Fi-information-connected-using-QR-Code

Settings -> Apps -> Special Access -> Wifi control -> QT & Barcode Scanner --> disable (and re-enable, if you like)
