### ISSUE TITLE
Postal address from VCard QR code is not recognized

### ISSUE THREAD

**Issue by TheFish123** [dmitriy-ilchenko/QrAndBarcodeScanner#46]
I've created some vcard QRs using https://www.qrcode-monkey.com/#vcard

When scanning these codes and trying to add a new contact to my address book, the postal address is ignored. But when I copy the text itself, I can see the address "ADR: ...". And the QR is recognized correctly with other scanner apps and on the iPhone.

**Comment by dmitriy-ilchenko** [comment]
Yes thats a bug. Thank you for reporting it. I will try to fix it in the next release.

**Comment by dmitriy-ilchenko** [comment]
Should be working in v1.6
