### ISSUE TITLE
Problems with special characters escaped with leading backslash in WiFi-passwords

### ISSUE THREAD

**Issue by sicherist** [dmitriy-ilchenko/QrAndBarcodeScanner#47]
QrAndBarcodeScanner Version 1.5

AVM "Fritzbox" routers (very widely used brand in Germany) display a QR-Code for WiFi-Setup. I encountered problems with the wifi password not working after having been decoded by your app. I will try to explain what I was able to figure out:

Some special characters in the wifi-password are escaped with a leading backslash in the qr-code. When scanning the qr-code the escape-backslashes should be removed (but not the backslashes that are actually part of the password), else the wifi password will not work.

Valid characters are (including blank spaces):
``_ - ! " # $ % & ' ( ) * + , . / : ; < = > ? @ [ \ ] ^ ` { | } ~``

As far as I could tell, characters that will be escaped, are: Quotation mark ("), apostrophe ('), comma (,), slash (/), colon (:), semicolon (;) and backslash (\\\).

If I create a wifi-password with all the characters mentioned above, the qr code generated by the router is this:

![grafik](https://user-images.githubusercontent.com/6120865/97224887-1a7e7c00-17d2-11eb-9549-a25b24320cb7.png)

Decoded this is:
``WIFI:S:Gatze;T:WPA;P:_ - ! \" # $ % & \' ( ) * + \, . \/ \: \; < = > ? @ [ \\ ] ^ ` { | } ~;;``

What I get when scanning the qr code with your app is this:

``_ - ! " # $ % & \' ( ) * + , . \/ : \``

So I see two problems here:

a) The password ends right before the semicolon which is part of the password and does not indicate the end of the password in this case. The escaping backslash before the semicolon is kept.
b) Some escaping backslashes are not removed (before apostrophe and before slash).

I am not really sure if the problem is in your app or if the router generates non-standard qr-codes (BTW: Where is this standard defined and what is it called?)

**Comment by dmitriy-ilchenko** [comment]
Thank you for reporting a bug. I fixed it and the bugfix will be available in the next release.

**Comment by dmitriy-ilchenko** [comment]
Should be working in v1.6
