### ISSUE TITLE
F-Droid build and Sentry

### ISSUE THREAD

**Issue by licaon-kter** [dmitriy-ilchenko/QrAndBarcodeScanner#49]
Since https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner/commit/d101bac7cad9c4f4e9c9b203ae522ad0c63b5755 `sentryDSN` is no longer in the repo.

Since F-Droid needs all the source code in the open, can we still use the old `https://09f3022eb19f4fa7ba332b1f44188ff1@o432234.ingest.sentry.io/5384638` ?

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7674/

**Comment by dmitriy-ilchenko** [comment]
Sorry for the inconvenience. I will fix the issue soon, could you please use the old key?

**Comment by licaon-kter** [comment]
I will use it, once you put it back in the repo in some form.

**Comment by TheFish123** [comment]
This is the reason why V1.6 has not arrived on F-Droid yet, right? Just wondering...

**Comment by licaon-kter** [comment]
Yes, that's holding it up.

I want to use a key, but none is available in the **current** code.

**Comment by dmitriy-ilchenko** [comment]
@licaon-kter Sorry for the delay, should be fixed in v1.7

**Comment by licaon-kter** [comment]
Thanks
