### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by locness3** [dmitriy-ilchenko/QrAndBarcodeScanner#71]
Feel free to close this issue.

I just wanted to congratulate you, @dimitriy-ilchenko, for this app's UI and UX. Many open-source Android apps have old, complex or just plain ugly UIs. Yours is clean and simple, modern and easy to use, yet it has many features. Thanks a lot for this app, and I wish there would be more like this.

**Comment by sheeepdev** [comment]
Same.
